// @vitest-environment node
import { parseSync, type Manifest } from "vite";
import { describe, expect, it } from "vitest";
import {
  DEFAULT_TEMPLATE,
  assetsFromManifest,
  clientEntry,
  devAssets,
  devTemplate,
  handlerModule,
  importPath,
  routesDts,
  serverEntry,
} from "../../src/vite/codegen";
import { scanPages } from "../../src/vite/scan";

const ROOT = "/app";
const DIR = `${ROOT}/src/pages`;
const PAGE = 'import { Page } from "nuclo-pages";\nexport default Page({ render: () => div() });';
const files: Record<string, string> = {
  "_layout.ts": 'import { Layout } from "nuclo-pages";\nexport default Layout({ render: ({ children }) => div(children) });',
  "index.ts": PAGE,
  "blog/[slug].ts": 'import { Page } from "nuclo-pages";\nexport default Page({ prerender: true, render: () => div() });',
  "docs/[...path].ts": PAGE,
  "api/health.ts": "export const GET = () => new Response();",
};
const scan = scanPages(DIR, (file) => files[file.slice(DIR.length + 1)], Object.keys(files));
const parses = (code: string) => expect(parseSync("gen.js", code).errors).toEqual([]);

describe("routesDts", () => {
  it("registers every route id with its params", () => {
    expect(routesDts(scan)).toBe(`// Generated by nuclo-pages from src/pages. Do not edit.
export {};

declare module "nuclo-pages" {
  interface Register {
    routes: {
      "/api/health": {};
      "/blog/[slug]": { slug: string };
      "/docs/[...path]": { path: string };
      "/": {};
    };
  }
}
`);
  });
});

describe("clientEntry", () => {
  const code = clientEntry(scan, ROOT, { base: "/", dev: false });

  it("loads nuclo first, then starts the router", () => {
    parses(code);
    expect(code.indexOf('import "nuclo";')).toBe(0);
    expect(code).toContain('import { start } from "nuclo-pages/client";');
    expect(code).toContain('base: "/"');
    expect(code).toContain("dev: false");
  });

  it("lazy-imports route modules but never API routes", () => {
    expect(code).toContain('() => import("/src/pages/blog/[slug].ts")');
    expect(code).not.toContain('import("/src/pages/api/health.ts")');
    expect(code).toMatch(/modules: \[[^\]]*null/);
  });

  it("ships the route table without build-only fields", () => {
    expect(code).not.toContain('"file"');
    expect(code).not.toContain('"prerender"');
    expect(code).toContain('"id":"/api/health"');
  });
});

describe("handlerModule", () => {
  const options = {
    root: ROOT,
    serverFns: { abc: "/src/server/posts.ts" },
    template: '<html><head><title>"quoted" </script></title><!--nuclo:head--></head><body><!--nuclo:body--></body></html>',
    assets: devAssets("/"),
    middleware: "/src/middleware.ts",
    base: "/",
    dev: true,
  };

  it("sets up the server runtime before anything else", () => {
    const code = handlerModule(scan, options);
    parses(code);
    expect(code.startsWith('import "nuclo/polyfill";\nimport "nuclo";\n')).toBe(true);
    expect(code).toContain('import middleware from "/src/middleware.ts";');
    expect(code).toContain('"abc": () => import("/src/server/posts.ts")');
    expect(code).toContain('() => import("/src/pages/api/health.ts")'); // the server imports API routes
    expect(code).toContain(JSON.stringify(options.template));
  });

  it("works without middleware and server functions", () => {
    const code = handlerModule(scan, { ...options, middleware: null, serverFns: {} });
    parses(code);
    expect(code).toContain("const middleware = undefined;");
    expect(code).toContain("serverFns: {}");
  });
});

describe("dev helpers", () => {
  it("serves the client entry through Vite and loads Vite's client", () => {
    expect(devAssets("/base/").entry.js).toBe("/base/@id/__x00__virtual:nuclo-pages/client-entry");
    expect(devTemplate(DEFAULT_TEMPLATE, "/")).toContain('<script type="module" src="/@vite/client"></script><!--nuclo:head-->');
  });

  it("has a default template with both placeholders", () => {
    expect(DEFAULT_TEMPLATE).toContain("<!--nuclo:head-->");
    expect(DEFAULT_TEMPLATE).toContain("<!--nuclo:body-->");
  });

  it("serverEntry serves the built client with the chosen adapter", () => {
    for (const adapter of ["node", "bun"] as const) {
      const code = serverEntry(adapter);
      parses(code);
      expect(code).toContain(`from "nuclo-pages/${adapter}"`);
      expect(code).toContain('new URL("../client/", import.meta.url)');
    }
  });

  it("importPath is root-relative with forward slashes", () => {
    expect(importPath("/app", "/app/src/pages/index.ts")).toBe("/src/pages/index.ts");
  });
});

describe("assetsFromManifest", () => {
  const manifest: Manifest = {
    "virtual:nuclo-pages/client-entry": { file: "assets/entry-1.js", isEntry: true, imports: ["_nuclo-2.js"], css: ["assets/entry.css"] },
    "_nuclo-2.js": { file: "assets/nuclo-2.js", imports: ["_deep-3.js"] },
    "_deep-3.js": { file: "assets/deep-3.js", css: ["assets/deep.css"], imports: ["_nuclo-2.js"] }, // cycle
    "src/pages/_layout.ts": { file: "assets/layout.js", isDynamicEntry: true, imports: ["_nuclo-2.js"], css: ["assets/layout.css"] },
    "src/pages/index.ts": { file: "assets/index.js", isDynamicEntry: true },
    "src/pages/blog/[slug].ts": { file: "assets/slug.js", isDynamicEntry: true, imports: ["_nuclo-2.js", "_missing.js"] },
  };

  it("collects each module's chunk, imported chunks and CSS transitively", () => {
    const assets = assetsFromManifest(manifest, scan, ROOT, "/base/");
    expect(assets.entry).toEqual({
      js: "/base/assets/entry-1.js",
      css: ["/base/assets/entry.css", "/base/assets/deep.css"],
      preload: ["/base/assets/nuclo-2.js", "/base/assets/deep-3.js"],
    });
    const byFile = Object.fromEntries(scan.modules.map((m, i) => [m.file.slice(DIR.length + 1), assets.modules[i]]));
    expect(byFile["_layout.ts"]).toEqual({
      js: "/base/assets/layout.js",
      css: ["/base/assets/layout.css", "/base/assets/deep.css"],
      preload: ["/base/assets/nuclo-2.js", "/base/assets/deep-3.js"],
    });
    expect(byFile["index.ts"]).toEqual({ js: "/base/assets/index.js", css: [], preload: [] });
    expect(byFile["blog/[slug].ts"]!.preload).toEqual(["/base/assets/nuclo-2.js", "/base/assets/deep-3.js"]);
    // Not in the client build: the API route and a module missing from the manifest.
    expect(byFile["api/health.ts"]).toBeNull();
    expect(byFile["docs/[...path].ts"]).toBeNull();
  });

  it("requires an entry", () => {
    expect(() => assetsFromManifest({}, scan, ROOT, "/")).toThrow("has no entry");
  });
});
