import { relative } from "node:path";
import { normalizePath, type Manifest } from "vite";
import type { AssetSet, Assets } from "../server/render";
import type { PagesScan, ScannedRoute } from "./scan";

export const DEFAULT_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--nuclo:head-->
  </head>
  <body>
    <!--nuclo:body-->
  </body>
</html>
`;

/** Root-relative import specifier ("/src/pages/index.ts") for an absolute file. */
export const importPath = (root: string, file: string) => "/" + normalizePath(relative(root, file));

const lazy = (root: string, file: string) => `() => import(${JSON.stringify(importPath(root, file))})`;

/** The route table without build-only fields. */
const routeTable = (routes: readonly ScannedRoute[]) => JSON.stringify(routes.map(({ file: _file, prerender: _prerender, ...route }) => route));

export function clientEntry(scan: PagesScan, root: string, options: { base: string; dev: boolean }): string {
  // API routes are server-only: the client table keeps their pattern (for a full navigation) but never imports them.
  const modules = scan.modules.map((m) => (m.server ? "null" : lazy(root, m.file)));
  return `import "nuclo";
import { start } from "nuclo-pages/client";

start({
  modules: [${modules.join(", ")}],
  routes: ${routeTable(scan.routes)},
  root: ${JSON.stringify(scan.root)},
  base: ${JSON.stringify(options.base)},
  dev: ${options.dev},
});
`;
}

export interface HandlerModuleOptions {
  root: string;
  /** Server function id → root-relative module path. */
  serverFns: Record<string, string>;
  template: string;
  assets: Assets;
  /** Root-relative path of src/middleware.*, if any. */
  middleware: string | null;
  base: string;
  dev: boolean;
}

export function handlerModule(scan: PagesScan, options: HandlerModuleOptions): string {
  const serverFns = Object.entries(options.serverFns).map(([id, file]) => `${JSON.stringify(id)}: () => import(${JSON.stringify(file)})`);
  return `import "nuclo/polyfill";
import "nuclo";
import { createHandler } from "nuclo-pages/server";
${options.middleware ? `import middleware from ${JSON.stringify(options.middleware)};` : "const middleware = undefined;"}

export default createHandler({
  modules: [${scan.modules.map((m) => lazy(options.root, m.file)).join(", ")}],
  routes: ${routeTable(scan.routes)},
  root: ${JSON.stringify(scan.root)},
  serverFns: {${serverFns.join(", ")}},
  template: ${JSON.stringify(options.template)},
  assets: ${JSON.stringify(options.assets)},
  middleware,
  base: ${JSON.stringify(options.base)},
  dev: ${options.dev},
});
`;
}

/** Entry of the Node/Bun server build: serves dist/client and the handler. */
export function serverEntry(adapter: "node" | "bun"): string {
  return `import handler from "virtual:nuclo-pages/handler";
import { serve } from "nuclo-pages/${adapter}";

serve(handler, { clientDir: new URL("../client/", import.meta.url) });
`;
}

/** `src/routes.gen.d.ts`: registers route ids and their params for typed `load`, `href` and props. */
export function routesDts(scan: PagesScan): string {
  const lines = scan.routes.map((route) => {
    const params = route.path.flatMap((segment) => {
      const name = /^\[(?:\.\.\.)?(.+)\]$/.exec(segment)?.[1];
      return name ? [`${name}: string`] : [];
    });
    return `      ${JSON.stringify(route.id)}: {${params.length ? ` ${params.join("; ")} ` : ""}};`;
  });
  return `// Generated by nuclo-pages from src/pages. Do not edit.
export {};

declare module "nuclo-pages" {
  interface Register {
    routes: {
${lines.join("\n")}
    };
  }
}
`;
}

/** Dev: no built files; Vite serves the client entry and its imports on demand. */
export function devAssets(base: string): Assets {
  return { entry: { js: `${base}@id/__x00__virtual:nuclo-pages/client-entry`, css: [], preload: [] }, modules: [] };
}

/** Dev: the template also loads Vite's client (HMR, error overlay). */
export function devTemplate(template: string, base: string): string {
  return template.replace("<!--nuclo:head-->", `<script type="module" src="${base}@vite/client"></script><!--nuclo:head-->`);
}

/** Build: per route module, its chunk plus the chunks and CSS it statically imports. */
export function assetsFromManifest(manifest: Manifest, scan: PagesScan, root: string, base: string): Assets {
  const collect = (key: string): AssetSet => {
    const css = new Set<string>();
    const preload = new Set<string>();
    const seen = new Set<string>();
    const visit = (name: string) => {
      const chunk = manifest[name];
      if (!chunk || seen.has(name)) return;
      seen.add(name);
      for (const file of chunk.css ?? []) css.add(base + file);
      for (const imported of chunk.imports ?? []) {
        if (manifest[imported]) preload.add(base + manifest[imported].file);
        visit(imported);
      }
    };
    visit(key);
    return { js: base + manifest[key].file, css: [...css], preload: [...preload] };
  };
  const entry = Object.keys(manifest).find((key) => manifest[key].isEntry);
  if (!entry) throw new Error("[nuclo-pages] the client build manifest has no entry");
  return {
    entry: collect(entry),
    modules: scan.modules.map((m) => {
      const key = normalizePath(relative(root, m.file));
      return m.server || !manifest[key] ? null : collect(key);
    }),
  };
}
