// Generated by nuclo-pages from src/pages. Do not edit.
export {};

declare module "nuclo-pages" {
  interface Register {
    routes: {
      "/about/life": {};
      "/api/health": {};
      "/blog/[slug]": { slug: string };
      "/about": {};
      "/blog": {};
      "/todos": {};
      "/": {};
    };
  }
}
