// Generated by nuclo-pages from src/pages. Do not edit.
export {};

declare module "nuclo-pages" {
  interface Register {
    routes: {
      "/api/health": {};
      "/posts/[slug]": { slug: string };
      "/counter": {};
      "/posts": {};
      "/": {};
    };
  }
}
