// Regenerates src/generated/nuclo-stats.ts from packages/nuclo-core
// (package version + gzipped size of dist/nuclo.mjs). Run via `bun run update:stats`.
import { join, resolve } from "node:path";

const docsDir = resolve(import.meta.dir, "..");
const coreDir = resolve(docsDir, "..", "packages", "nuclo-core");
const outFile = join(docsDir, "src", "generated", "nuclo-stats.ts");

const pkg = await Bun.file(join(coreDir, "package.json")).json();
const version: string = pkg.version;

const bundle = Bun.file(join(coreDir, "dist", "nuclo.mjs"));
if (!(await bundle.exists())) {
  console.error("packages/nuclo-core/dist/nuclo.mjs not found - run `bun run build` in packages/nuclo-core first.");
  process.exit(1);
}

const gzippedBytes = Bun.gzipSync(new Uint8Array(await bundle.arrayBuffer()), { level: 9 }).byteLength;
const gzipKb = (gzippedBytes / 1000).toFixed(1);

const content = `// Auto-generated by scripts/update-doc-stats.ts - do not edit by hand.
export const NUCLO_VERSION = "${version}";
export const NUCLO_GZIP_KB = "${gzipKb}";
`;

const existing = await Bun.file(outFile).exists() ? await Bun.file(outFile).text() : null;
if (existing === content) {
  console.log(`nuclo-stats.ts up to date (v${version}, ${gzipKb} KB gzipped)`);
} else {
  await Bun.write(outFile, content);
  console.log(`nuclo-stats.ts updated (v${version}, ${gzipKb} KB gzipped)`);
}
